### ISSUE TITLE
invalid line number

### ISSUE THREAD

**Issue by ericaro** [remyoudompheng/go-misc#4]
misplaced error:
for instance:

this file 

``` golang
package protocol

import "fmt"

const (
    a = 12
    b = 42
)

func Main() {
    fmt.Println(b)
}
```

reports `deadcode: deadcode.go:5:1: a is unused`

 line 5 is the 'const'  statement, it should be the 'a' statement instead (line 6 ).

**Comment by remyoudompheng** [comment]
This is fixed by commit 01514f0
