### ISSUE TITLE
reports error 'à la' go

### ISSUE THREAD

**Issue by ericaro** [remyoudompheng/go-misc#5]
Deadcode outputs are all prefixed with deadcode, go compilation does not use this kind of prefix, and this is not very useful.

Plus, it would be great if files path was relative to the $GOPATH
This would make deadcode errors looks like go compilation errors, and makes deadcode easier to integrate in any ide.

**Comment by remyoudompheng** [comment]
Fixed by commit  01514f0

Filenames are now relative to the working directory (this is the usual convention in go tools), and no longer prefixed by "deadcode:".

Also, the reported position is now the exact position of the unused variable declaration, which helps when dealing with long blocks like:

    var (
        x = 5
        y = 7
        z = 4
        [...]
        t = 1
    )

**Comment by etnz** [comment]
Thank you very much! I fill this is a great improvement for the tool
