### ISSUE TITLE
Deadcode should not detect "_ is unused"

### ISSUE THREAD

**Issue by cep21** [remyoudompheng/go-misc#6]
It's common in go to validate a type satisifies an interface with something like ```var _ io.Writer = &MyWriter{}```, however deadcode detects this.  Deadcode should not message on ```_``` assigned global variables.

**Comment by cep21** [comment]
Awesome.  Fixed!

**Comment by cep21** [comment]
oops not merged :/

**Comment by tsuna** [comment]
ping, can we get the fix merged?

**Comment by fsomers** [comment]
+1, would appreciate a release with this fix incorporated, thanks...

**Comment by tsuna** [comment]
ping?
